schema_version: 1

context:
  version: "0.7.0"

recipe:
  name: tinyopt-suite
  version: ${{ version }}

source:
  url: https://github.com/julien-michot/tinyopt/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 514adec614adf56d8cd869df12f8e937473d2f65fc8b33998d1df9d715c11485

build:
  number: 0

outputs:
  - package:
      name: tinyopt
      version: ${{ version }}
    build:
      number: 0
      script:
        - if: win
          then: build_tinyopt.bat
          else: build_tinyopt.sh
    requirements:
      build:
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - python >=3.12
        - cmake >=3.25
        - ninja
      host:
        - eigen >=3.4
      run:
        - eigen >=3.4
    tests:
      - package_contents:
          files:
            - ${{ "Library/include/tinyopt/tinyopt.h" if win else "include/tinyopt/tinyopt.h" }}
            - ${{ "Library/lib/cmake/Tinyopt/TinyoptConfig.cmake" if win else "lib/cmake/Tinyopt/TinyoptConfig.cmake" }}
            - ${{ "Library/share/doc/tinyopt/3rdparty/ceres/LICENSE" if win else "share/doc/tinyopt/3rdparty/ceres/LICENSE" }}

  - package:
      name: tinyopt-doc
      version: ${{ version }}
    build:
      number: 0
      script:
        - if: win
          then: build_tinyopt_docs.bat
          else: build_tinyopt_docs.sh
    requirements:
      build:
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - python >=3.12
        - cmake >=3.25
        - ninja
        - doxygen >=1.10
        - sphinx <8
        - breathe >=4.35
        - sphinx-rtd-theme >=1.0
        - myst-parser >=2.0
      host:
        - eigen >=3.4
      run:
        - eigen >=3.4
    tests:
      - package_contents:
          files:
            - ${{ "Library/share/doc/tinyopt/3rdparty/ceres/LICENSE" if win else "share/doc/tinyopt/3rdparty/ceres/LICENSE" }}
            - ${{ "Library/share/doc/tinyopt/guide/index.html" if win else "share/doc/tinyopt/guide/index.html" }}

about:
  homepage: https://github.com/julien-michot/tinyopt
  license: Apache-2.0
  license_file: LICENSE
  summary: A lightweight, header-only C++20 optimization library
  description: |
    Tinyopt is a super fast header-only C++20 library for unconstrained optimization and nonlinear least squares.
  repository: https://github.com/julien-michot/tinyopt
  documentation: https://github.com/julien-michot/tinyopt

extra:
  recipe-maintainers:
    - julien-michot
